# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 578ab03fd3ff29381dd7224b3e9982eed959ce59c9c1c8088590e0e072fade59fbc657bfc236bf6801af0cc8d76e6cccce6129d8f806f653ffd4daf10cf6f6c5

test:
  secret_key_base: 2d3e18da050044fb4a83b87d5e8d36e8349c838afd5b44a5e8ecf36580a8c9f5a504275b50e7df0ddf0f813d83c59b15907c794e71c141e8960460cd4e30b39f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
